version: '3'

services:
  registry:
    image: registry:2.8
    container_name: registry
    restart: always
    hostname: registry
    ports:
      - '5050:5000'
    volumes:
      - ./Registry/registry:/var/lib/registry

  registry-frontend:
    image: konradkleine/docker-registry-frontend:v2
    container_name: registry-frontend
    hostname: registry-frontend
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000
    ports:
      - '8000:80'