version: '3'

services:
  training:
    build:
      context: MachineLarning
      dockerfile: Dockerfile
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
    user: root
    ports:
      - '8888:8888'
    # volumes:
    #   - ./MachineLarning/work/data:/home/data
    #   - ./trainedDNN:/home/trainedDNN
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  webapp:
    image: localhost:5050/mywebapp
    container_name: flask
    user: root
    # command: ["bash"]
    tty: true
    ports:
      - '5000:5000'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  storage:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadminuser
      - MINIO_ROOT_PASSWORD=minioadminpassword
    entrypoint: bash
    command: -c "/opt/bin/minio server /export --address :9000 --console-address :9001"
    volumes:
      - ./DataStorage:/export
    ports:
      - 9000:9000
      - 9001:9001

  database:
    image: mysql
    container_name: mysql
    ports:
     - 3306:3306
    env_file:
     - ./DataBase/.env_mysql
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
      # - type: bind
      #   source: ./DataBase/init
      #   target: /docker-entrypoint-initdb.d

volumes:
  mysql-data:
    name: mysql-volume