version: '3'
services:
  training:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    ports:
      - '8888:8888'
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./work/data:/home/data
      - ../trainedDNN:/home/trainedDNN
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # command: bash