version: '3'
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.dev
    user: root
    ports:
      - '8888:8888'
    environment:
      - GRANT_SUDO=yes
      - TZ=Asia/Tokyo
    volumes:
      - ./work:/home/jovyan/work
      - ../trainedDNN:/home/jovyan/trainedDNN
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: start-notebook.sh --NotebookApp.password=''