version: '3'
services:
  training:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
    user: root
    ports:
      - '8888:8888'
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./work/data:/home/data
      - ../trainedDNN:/home/trainedDNN
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]