version: '3'
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - no_proxy=${NO_PROXY}
    user: root
    ports:
      - '5555:5000'
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    # command: bash